server:
  port: 80

spring:
  profiles:
    active: ${profileActive}
  application:
    name: gateway-server

logging:
  config: classpath:config/logback/logback-spring.xml

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

