spring:
  profiles:
    active: ${profileActive}
  application:
    name: gateway-manager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:config/logback/logback-spring.xml

mybatis:
  type-aliases-package: com.weweibuy.gateway.manager.model.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml  # mapper映射文件

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #选择暴露的端点  info,health,env,beans
        #不暴露的端点
        #exclude=env
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节。
